package com.plural_pinelabs.expresscheckoutsdk.common

internal object Constants {
    const val MOBILE_REGEX =
        "^[+]?\\d{1,4}[\\s-]?\\(?\\d{1,4}\\)?[\\s-]?\\d{1,4}[\\s-]?\\d{1,4}$"
    const val EMAIL_REGEX = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$"
    const val BASE_URL_UAT = "pluraluat.v2.pinepg.in"
    const val BASE_URL_QA = "pluralqa.pinepg.in"
    const val BASE_URL_EXPRESS_DEV = "nxt-express-checkout-svc-dev.v2.pinepg.in"
    const val BASE_URL_PROD = "api.pluralonline.com"
    const val BASE_ANIMATION = "https://d1xlp3rxzdtgvz.cloudfront.net/loaderAnimation/"
    const val BASE_IMAGES = "https://d1xlp3rxzdtgvz.cloudfront.net/bank-icons/bank-logos/"
    const val HTTPS = "https://"
    const val BASE_CHECKOUTBFF = "/api/v3/checkout-bff/"

    const val TIMEOUT: Long = 60

    const val CREDIT_DEBIT_ID = "CREDIT_DEBIT"
    const val PAY_BY_POINTS_ID = "PAYBYPOINTS"
    const val NET_BANKING_ID = "NET_BANKING"
    const val UPI_ID = "UPI"
    const val WALLET_ID = "WALLET"
    const val EMI_ID = "EMI"
    const val DEBIT_EMI_ID = "DEBIT_EMI"


    const val CARD_NUMBER_CHUNK = 4
    const val PAYMENT_REFERENCE_TYPE_CARD = "CARD"

    const val BROWSER_ACCEPT_ALL = "*/*"
    const val BROWSER_USER_AGENT_ANDROID =
        "Mozilla/5.0+(Macintosh;+Intel+Mac+OS+X+10_15_7)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/133.0.0.0+Safari/537.36"
    const val BROWSER_DEVICE_CHANNEL = "browser"
    const val TRANSACTION_TYPE_SDK = "SDK"
    const val SDK_TYPE = "ANDROID"
    const val PLATFORM_TYPE = "NATIVE_MOBILE"
    const val OS = "Android"
    const val PLATFORM_VERSION = "v3"
    const val APP_VERSION = "1.0"

    const val IMAGE_LOGO = BASE_ANIMATION + "logo_shimmer.json"
    const val BFF_RESPONSE_HANDLER_ENDPOINT = "checkout-bff/responseHandler"
    const val ACS_JAVA_SCRIPT_INTERFACE = "AndroidInterface"

    //UPI
    const val UPI_INTENT_PREFIX = "upi://pay"
    const val GPAY = "com.google.android.apps.nbu.paisa.user"
    const val PHONEPE = "com.phonepe.app"
    const val PAYTM = "net.one97.paytm"
    const val BHIM_UPI = "in.org.npci.upiapp"
    const val CRED_UPI = "com.dreamplug.androidapp"
    const val UPI_INTENT = "INTENT"
    const val UPI_COLLECT = "COLELCT"
    const val UPI_TRANSACTION_STATUS_INTERVAL = 5000L


    const val PROCESSED_STATUS = "PROCESSED"
    const val PROCESSED_PENDING = "PENDING"
    const val PROCESSED_FAILED = "FAILED"
    const val PROCESSED_ATTEMPTED = "ATTEMPTED"
    const val PROCESSED_CREATED = "CREATED"

    const val REQ_USER_CONSENT = 200

    const val ERROR_KEY = "Error"
    const val ERROR_MESSAGE_KEY = "ErrorMessage"

    //bank code
    const val AXIS_BANK_CODE = "NB1004"
    const val HDFC_BANK_CODE = "NB1007"
    const val JK_BANK_CODE = "NB1015"
    const val ICICI_BANK_CODE = "NB1016"
    const val FEDERAL_BANK_CODE = "NB1029"
    const val KARNATAKA_BANK_CODE = "NB1133"
    const val CORPORATION_BANK_CODE = "NB1135"
    const val INDIAN_BANK_CODE = "NB1143"
    const val YES_BANK_CODE = "NB1146"
    const val CENTRAL_BANK_CODE = "NB1147"
    const val KOTAK_BANK_CODE = "NB1148"
    const val ORIENTAL_BANK_CODE = "NB1154"
    const val UNITED_BANK_CODE = "NB1212"
    const val INDIAN_OVERSEAS_BANK_CODE = "NB1213"
    const val CITY_UNION_BANK_CODE = "NB1215"
    const val UNION_BANK_CODE = "NB1216"
    const val CANARA_BANK_CODE = "NB1224"
    const val MAHARASHTRA_BANK_CODE = "NB1229"
    const val CATHOLIC_SYRIAN_BANK_CODE = "NB1272"
    const val DHANLAXMI_BANK_CODE = "NB1373"
    const val ANDHRA_BANK_CODE = "NB1378"
    const val VIJAYA_BANK_CODE = "NB1379"
    const val SARASWAT_BANK_CODE = "NB1380"
    const val PNB_BANK_CODE = "NB1381"
    const val UCO_BANK_CODE = "NB1483"
    const val PUNJAB_AND_SINDH_BANK_CODE = "NB1421"
    const val INDUSIND_BANK_CODE = "NB1431"
    const val TAMILNAD_MERCHANTILE_BANK_CODE = "NB1439"
    const val COSMOS_BANK_CODE = "NB1488"
    const val PNB_CORPORATE_BANK_CODE = "NB1489"
    const val ANDHRA_CORPORATE_BANK_CODE = "NB1484"
    const val BARODA_BANK_CODE = "NB1485"
    const val BAHRAIN_AND_KUWAIT_BANK_CODE = "NB1486"
    const val BARODA_RETAIL_BANK_CODE = "NB1487"
    const val DEDUSCHE_BANK_CODE = "NB1490"
    const val DEVELOPMENT_CREDIT_BANK_CODE = "NB1491"
    const val DENA_BANK_CODE = "NB1492"
    const val IDBI_BANK_CODE = "NB1493"
    const val KARUR_VYSYA_BANK_CODE = "NB1494"
    const val LAXMI_VILAS_BANK_CODE = "NB1495"
    const val LAXMI_VILAS_BANK_RETAIL_CODE = "NB1496"
    const val PUNJAB_MAHARASHTRA_BANK_CODE = "NB1497"
    const val STANDARD_CHARTERED_BANK_CODE = "NB1498"
    const val SOUTH_INDIAN_BANK_CODE = "NB1499"
    const val SHAMRO_VITHAL_BANK_CODE = "NB1500"
    const val SYNDICATE_BANK_CODE = "NB1501"
    const val TAMIL_NADU_STATE_COOP_BANK_CODE = "NB1502"
    const val JANATA_SAHAKARI_BANK_CODE = "NB1503"
    const val NKGSB_BANK_CODE = "NB1504"
    const val TJSB_BANK_CODE = "NB1505"
    const val KALYAN_JANATA_BANK_CODE = "NB1506"
    const val MEHSANA_URBAN_BANK_CODE = "NB1507"
    const val BANDHAN_BANK_CODE = "NB1508"
    const val DIGIBANK_BANK_CODE = "NB1509"
    const val IDFC_FIRST_BANK_CODE = "NB1510"
    const val BASSIEN_BANK_CODE = "NB1511"
    const val PNB_YUVA_BANK_CODE = "NB1512"
    const val RBL_BANK_CODE = "NB1513"
    const val THE_KALUPUR_BANK_CODE = "NB1514"
    const val EQUITAS_BANK_CODE = "NB1515"
    const val THANE_BHARAT_BANK_CODE = "NB1516"
    const val SURYODAY_BANK_CODE = "NB1517"
    const val ESAF_BANK_CODE = "NB1518"
    const val VARACHHA_BANK_CODE = "NB1519"
    const val NORTH_EAST_BANK_CODE = "NB1520"
    const val IDBI_CORPORATE_BANK_CODE = "NB1521"
    const val YES_CORPORATE_BANK_CODE = "NB1522"
    const val CORPORATION_CORPORATE_BANK_CODE = "NB1523"
    const val RBL_CORPORATE_BANK_CODE = "NB1524"
    const val SHAMRO_VITHAL_CORPORATE_BANK_CODE = "NB1525"
    const val DHANLAXMI_CORPORATE_BANK_CODE = "NB1526"
    const val BARCLAYS_BANK_CODE = "NB1527"
    const val ZOROASTRAIN_BANK_CODE = "NB1528"
    const val AU_SMALL_FINANCE_BANK_CODE = "NB1529"
    const val ALLAHABAD_BANK_CODE = "NB1530"
    const val SBI_BANK_CODE = "NB1531"
    const val FINCARE_BANK_CODE = "NB1532"
    const val BANDHAN_BANK_CORPORATE_CODE = "NB1533"
    const val KARNATAKA_GRAMIN_BANK_CODE = "NB1534"
    const val DEFAULT_BANK_CODE = "0"

    //BANK Images endpoints
    const val AXIS = "axis_bank.svg"
    const val HDFC = "hdfc_bank.svg"
    const val JK = "jk_bank.svg"
    const val ICICI = "icici_bank.svg"
    const val FEDERAL = "federal_bank.svg"
    const val KARNATAKA = "karnataka_bank.svg"
    const val CORPORATION = "corporation_bank.svg"
    const val INDIAN = "indian_bank.svg"
    const val YES = "yes_bank.svg"
    const val CENTRAL = "central_bank.svg"
    const val KOTAK = "kotak_bank.svg"
    const val ORIENTAL = "oriental_bank.png"
    const val UNITED_BANK = "united_bank_of_india.png"
    const val INDIAN_OVERSEAS = "indian_overseas_bank.svg"
    const val CITY_UNION = "city_union_bank.svg"
    const val UNION_BANK = "union_bank_of_india.svg"
    const val CANARA_BANK = "canara_bank.svg"
    const val MAHARASHTRA_BANK = "bank_of_maharashtra.svg"
    const val CATHOLIC_SYRIAN = "catholic_syrian_bank.svg"
    const val DHANALAKSHMI = "dhanalakshmi_bank.svg"
    const val ANDHRA = "andhra_bank.svg"
    const val VIJAYA = "vijaya_bank.png"
    const val SARASWAT = "saraswat_bank.svg"
    const val PNB = "punjab_national_bank.svg"
    const val UCO = "uco_bank.svg"
    const val PUNJAB_AND_SINDH = "punjab_and_sindh_bank.svg"
    const val INDUSIND = "indusind.svg"
    const val TAMINAD_MERCHANTILE = "tamilnad_mercantile_bank.svg"
    const val COSMOS = "cosmos_bank.svg"
    const val PNB_CORPORATE = "punjab_national_bank.svg"
    const val ANDHRA_CORPORATE = "andhra_bank.svg"
    const val BARODA = "bank_of_baroda.svg"
    const val BAHRAIN_KUWAIT = "bank_of_bahrain_and_kuwait.svg"
    const val BARODA_RETAIL = "bank_of_baroda.svg"
    const val DEDUSHE = "deutsche_bank.svg"
    const val DEVELOPMENT = "development_credit_bank.svg"
    const val DENA = "dena_bank.svg"
    const val IDBI = "idbi_bank.svg"
    const val KARUR = "karur_vysya_bank.svg"
    const val LAXMI_VILAS = "laxmi_vilas_bank.svg"
    const val LAXMI_VILAS_RETAIL = "laxmi_vilas_bank.svg"
    const val PUNJAB_MAHARASHTRA = "punjab_and_maharashtra.png"
    const val STANDARD_CHARTERED_BANK = "standard_chartered_bank.svg"
    const val SOUTH_INDIAN_BANK = "south_indian_bank.svg"
    const val SHAMRO = "shamro.png"
    const val SYNDICATE = "syndicate_bank.svg"
    const val TAMIL_NADU_STATE_COORP = "tamil_nadu.png"
    const val JANATA = "janata.png"

    //const val NKGSB = "nkgsb_co_op_bank.svg"
    const val TJSB = "tjsb.png"
    const val KALYAN_JANATA = "kalyan_janata.png"
    const val MEHSANA = "mehsana.png"
    const val BANDHAN = "bandhan_bank.svg"

    //const val DIGIBANK = ".svg"
    const val IDFC = "idfc_first_bank.svg"
    const val BASSIEN = "bassien.png"

    //const val PNB_YUVA = ".svg"
    const val RBL = "rbl_bank_limited.svg"
    const val KALUPUR = "kalupur.png"

    //const val EQUITAS = "equitas_small_finance_bank.svg"
    const val THANE = "thane.png"
    const val SURYODAY = "suryoday.png"
    const val ESAF = "esaf_small_finance_bank.svg"
    const val VARACHHA = "varacha.png"
    const val NORTH_EAST = "north_east.png"
    const val IDBI_CORPORATE = "idbi_bank.svg"
    const val YES_CORPORATE = "yes_bank.svg"
    const val CORPORATION_CORPORATE = "corporation_bank.svg"
    const val RBL_CORPORATE = "rbl_bank_limited.svg"
    const val SHAMRO_CORPORATE = "shamro.png"
    const val DHANLAKSHMI = "dhanalakshmi_bank.svg"
    const val BARCLAYS = "barclays_bank.svg"
    const val ZOROASTRAIN = "zoroastrian.png"
    const val AU = "au_small_finance_bank.svg"
    const val ALLAHABAD = "allahabad_bank.svg"
    const val SBI = "state_bank_of_india.svg"
    const val FINCARE = "fincare.png"
    const val BANDHAN_CORPORATE = "bandhan_bank.svg"
    const val KARNATAKA_GRAMIN = "karnataka_gramin.png"

    const val NET_BANKING = "NETBANKING"

    //EMi
    const val EMI_CC_TYPE = "CC_BANK"
    const val EMI_DC_TYPE = "DC_BANK"
    const val EMI_CASHLESS_TYPE = "CASHLESS"

    //Bundle key
    const val ISSUE_ID = "issueId"
    const val TENURE_ID = "tenureId"

    const val AXIS_TITLE = "AXIS"
    const val HDFC_TITLE = "HDFC"
    const val JK_TITLE = "JK"
    const val ICICI_TITLE = "ICICI"
    const val FEDERAL_TITLE = "FEDERAL"
    const val KARNATAKA_TITLE = "KARNATAKA"
    const val CORPORATION_TITLE = "CORPORATION"
    const val INDIAN_TITLE = "INDIAN"
    const val YES_TITLE = "YES"
    const val CENTRAL_TITLE = "CENTRAL"
    const val KOTAK_TITLE = "KOTAK"
    const val ORIENTAL_TITLE = "ORIENTAL"
    const val UNITED_TITLE = "UNITED"
    const val INDIAN_OVERSEAS_TITLE = "INDIAN_OVERSEAS"
    const val CITY_UNION_TITLE = "CITY_UNION"
    const val UNION_TITLE = "UNION"
    const val CANARA_TITLE = "CANARA"
    const val MAHARASHTRA_TITLE = "MAHARASHTRA"
    const val CATHOLIC_SYRIAN_TITLE = "CATHOLIC_SYRIAN"
    const val DHANLAXMI_TITLE = "DHANLAXMI"
    const val ANDHRA_TITLE = "ANDHRA"
    const val VIJAYA_TITLE = "VIJAYA"
    const val SARASWAT_TITLE = "SARASWAT"
    const val PNB_TITLE = "PNB"
    const val UCO_TITLE = "UCO"
    const val PUNJAB_AND_SINDH_TITLE = "PUNJAB_AND_SINDH"
    const val INDUSIND_TITLE = "INDUSIND"
    const val TAMILNAD_MERCHANTILE_TITLE = "TAMILNAD_MERCHANTILE"
    const val COSMOS_TITLE = "COSMOS"
    const val PNB_CORPORATE_TITLE = "PNB_CORPORATE"
    const val ANDHRA_CORPORATE_TITLE = "ANDHRA_CORPORATE"
    const val BARODA_TITLE = "BARODA"
    const val BAHRAIN_AND_KUWAIT_TITLE = "BAHRAIN_AND_KUWAIT"
    const val BARODA_RETAIL_TITLE = "BARODA_RETAIL"
    const val DEDUSCHE_TITLE = "DEDUSCHE"
    const val DEVELOPMENT_CREDIT_TITLE = "DEVELOPMENT_CREDIT"
    const val DENA_TITLE = "DENA"
    const val IDBI_TITLE = "IDBI"
    const val KARUR_VYSYA_TITLE = "KARUR_VYSYA"
    const val LAXMI_VILAS_TITLE = "LAXMI_VILAS"
    const val LAXMI_VILAS_RETAIL_TITLE = "LAXMI_VILAS_RETAIL"
    const val PUNJAB_MAHARASHTRA_TITLE = "PUNJAB_MAHARASHTRA"
    const val STANDARD_CHARTERED_TITLE = "STANDARD_CHARTERED"
    const val SOUTH_INDIAN_TITLE = "SOUTH_INDIAN"
    const val SHAMRO_VITHAL_TITLE = "SHAMRO_VITHAL"
    const val SYNDICATE_TITLE = "SYNDICATE"
    const val TAMIL_NADU_STATE_COOP_TITLE = "TAMIL_NADU_STATE_COOP"
    const val JANATA_SAHAKARI_TITLE = "JANATA_SAHAKARI"
    const val NKGSB_TITLE = "NKGSB"
    const val TJSB_TITLE = "TJSB"
    const val KALYAN_JANATA_TITLE = "KALYAN_JANATA"
    const val MEHSANA_URBAN_TITLE = "MEHSANA_URBAN"
    const val BANDHAN_TITLE = "BANDHAN"
    const val DIGIBANK_TITLE = "DIGIBANK"
    const val IDFC_FIRST_TITLE = "IDFC_FIRST"
    const val BASSIEN_TITLE = "BASSIEN"
    const val PNB_YUVA_TITLE = "PNB_YUVA"
    const val RBL_TITLE = "RBL"
    const val THE_KALUPUR_TITLE = "THE_KALUPUR"
    const val EQUITAS_TITLE = "EQUITAS"
    const val THANE_BHARAT_TITLE = "THANE_BHARAT"
    const val SURYODAY_TITLE = "SURYODAY"
    const val ESAF_TITLE = "ESAF"
    const val VARACHHA_TITLE = "VARACHHA"
    const val NORTH_EAST_TITLE = "NORTH_EAST"
    const val IDBI_CORPORATE_TITLE = "IDBI_CORPORATE"
    const val YES_CORPORATE_TITLE = "YES_CORPORATE"
    const val CORPORATION_CORPORATE_TITLE = "CORPORATION_CORPORATE"
    const val RBL_CORPORATE_TITLE = "RBL_CORPORATE"
    const val SHAMRO_VITHAL_CORPORATE_TITLE = "SHAMRO_VITHAL_CORPORATE"
    const val DHANLAXMI_CORPORATE_TITLE = "DHANLAXMI_CORPORATE"
    const val BARCLAYS_TITLE = "BARCLAYS"
    const val ZOROASTRAIN_TITLE = "ZOROASTRAIN"
    const val AU_SMALL_FINANCE_TITLE = "AU_SMALL_FINANCE"
    const val ALLAHABAD_TITLE = "ALLAHABAD"
    const val SBI_TITLE = "SBI"
    const val FINCARE_TITLE = "FINCARE"
    const val BANDHAN_CORPORATE_TITLE = "BANDHAN_CORPORATE"
    const val KARNATAKA_GRAMIN_TITLE = "KARNATAKA_GRAMIN"
    const val DEFAULT_TITLE = "DEFAULT"

    const val DISPLAY_NAME_SUFFIX = " BANK"

    const val NO_COST_EMI = "NO_COST"
    const val LOW_COST_EMI= "LOW_COST"
    const val STANDARD_EMI="STANDARD"

    const val PDF_VIEWER_GOOGLE_DOC_URL= "https://docs.google.com/gview?embedded=true&url="



}